background #322f2f
selection_background #f0eaea
foreground #8d8989
selection_foreground #322f2f
font_family OverpassM Nerd Font
cursor #fffbfb
color0 #8d8989
color1 #c56a70
color2 #3b9e75
color3 #b37d21
color4 #528dcb
color5 #b76c9e
color6 #009d9c
color7 #322f2f
color8 #f0eaea
color9 #ffd9e1
color10 #c8e6d3
color11 #f9dab1
color12 #cedff8
color13 #fad4e9
color14 #c3e5e4
color15 #5e5a5a
