background #322f2f
selection_background #fffbfb
foreground #d5d1d1
selection_foreground #322f2f
font_family OverpassM Nerd Font
cursor #fffbfb
color0 #d5d1d1
color1 #cd6869
color2 #569c67
color3 #c07726
color4 #4d91c7
color5 #b66cac
color6 #229ca0
color7 #322f2f
color8 #fffbfb
color9 #ffa3a4
color10 #91dca0
color11 #ffb565
color12 #95ceff
color13 #f9a8ee
color14 #71dbe0
color15 #4f4c4c
